CREATE TABLE [dbo].[membership_master] (
    [id]                          INT              IDENTITY (1, 1) NOT NULL,
    [status]                      VARCHAR (50)     CONSTRAINT [DF_membership_master_status] DEFAULT ('Pending') NOT NULL,
    [name]                        NVARCHAR (50)    NULL,
    [xkey]                        VARCHAR (50)     NULL,
    [last_renewal_dt]             DATETIME2 (7)    NULL,
    [street1]                     NVARCHAR (50)    NULL,
    [street2]                     NVARCHAR (50)    NULL,
    [city]                        NVARCHAR (50)    NULL,
    [state]                       NVARCHAR (50)    NULL,
    [country]                     NVARCHAR (50)    NULL,
    [zip]                         VARCHAR (50)     NULL,
    [telephone1]                  VARCHAR (50)     NULL,
    [active]                      VARCHAR (50)     NULL,
    [source]                      NVARCHAR (250)   NULL,
    [join_date]                   DATETIME2 (7)    NULL,
    [share_address_internal]      VARCHAR (50)     NULL,
    [share_phone_internal]        VARCHAR (50)     NULL,
    [share_email_internal]        VARCHAR (50)     NULL,
    [share_address_external]      VARCHAR (50)     NULL,
    [share_phone_external]        VARCHAR (50)     NULL,
    [share_email_external]        VARCHAR (50)     NULL,
    [create_date]                 DATETIME2 (7)    NULL,
    [print_directory]             VARCHAR (50)     NULL,
    [priv]                        INT              CONSTRAINT [DF_membership_master_priv] DEFAULT ((0)) NOT NULL,
    [email]                       NVARCHAR (100)   NULL,
    [birth_date]                  DATETIME2 (7)    NULL,
    [yearly_miles]                INT              NULL,
    [publish_info]                VARCHAR (10)     NULL,
    [interest]                    NVARCHAR (2000)  NULL,
    [gender]                      NVARCHAR (25)    NULL,
    [fav_quote]                   NVARCHAR (250)   NULL,
    [hometown]                    NVARCHAR (50)    NULL,
    [rel_status]                  NVARCHAR (25)    NULL,
    [work_job_title]              NVARCHAR (25)    NULL,
    [work_profession]             NVARCHAR (2000)  NULL,
    [club_benefit]                NVARCHAR (2000)  NULL,
    [ed_university]               NVARCHAR (50)    NULL,
    [ed_class_year]               INT              NULL,
    [ed_degree]                   NVARCHAR (50)    NULL,
    [emergency_contact_name]      NVARCHAR (50)    NULL,
    [emergency_contact_telephone] NVARCHAR (50)    NULL,
    [telephone2]                  NVARCHAR (50)    NULL,
    [lupdate]                     DATETIME2 (7)    NULL,
    [main_member_id]              INT              NULL,
    [first_name]                  NVARCHAR (50)    NULL,
    [last_name]                   NVARCHAR (50)    NULL,
    [rleader_contact_pref]        NVARCHAR (50)    NULL,
    [rleader_mobile_pub]          BIT              CONSTRAINT [DF_membership_master_rleader_mobile_pub] DEFAULT ((0)) NOT NULL,
    [rleader_phone_pub]           BIT              CONSTRAINT [DF_membership_master_rleader_phone_pub] DEFAULT ((0)) NOT NULL,
    [rleader_email_pub]           BIT              CONSTRAINT [DF_membership_master_rleader_email_pub] DEFAULT ((1)) NOT NULL,
    [ride_announcement]           BIT              CONSTRAINT [DF_membership_master_ride_announcement] DEFAULT ((1)) NOT NULL,
    [volunteer_lead_ride]         BIT              CONSTRAINT [DF_membership_master_volunteer_lead_ride] DEFAULT ((0)) NOT NULL,
    [volunteer_meeting]           BIT              CONSTRAINT [DF_membership_master_volunteer_meeting] DEFAULT ((0)) NOT NULL,
    [volunteer_social]            BIT              CONSTRAINT [DF_membership_master_volunteer_social] DEFAULT ((0)) NOT NULL,
    [volunteer_newsletter]        BIT              CONSTRAINT [DF_membership_master_volunteer_newsletter] DEFAULT ((0)) NOT NULL,
    [volunteer_publicity]         BIT              CONSTRAINT [DF_membership_master_volunteer_publicity] DEFAULT ((0)) NOT NULL,
    [volunteer_invitational]      BIT              CONSTRAINT [DF_membership_master_volunteer_invitational] DEFAULT ((0)) NOT NULL,
    [volunteer_events]            BIT              CONSTRAINT [DF_membership_master_volunteer_events] DEFAULT ((0)) NOT NULL,
    [guid]                        UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [picture_id]                  INT              NULL,
    [officer_title]               NVARCHAR (200)   NULL,
    [officer_order]               INT              NULL,
    CONSTRAINT [PK_membership_master] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_membership_master_membership_master] FOREIGN KEY ([main_member_id]) REFERENCES [dbo].[membership_master] ([id]),
    CONSTRAINT [FK_membership_master_vcontent] FOREIGN KEY ([picture_id]) REFERENCES [dbo].[vcontent] ([id])
);

